CREATE DATABASE IF NOT EXISTS zkteste;
USE zkteste;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL UNIQUE,
    PRIMARY KEY (id)
);
